config/routes.rb
CoachApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { registrations: "registrations" }

  resources :contacts
  resources :events
  resources :friendships #, only: [:delete]
  resources :invitations, except: [:show, :edit]
  resources :messages, only: [:index, :sent, :show, :destroy] do
    collection do
      get 'sent'
    end
  end
  resources :parameters
  resources :people do
    resources :messages, only: [:new, :create]
    resources :invitations do # , only: [:create] do
      collection do
        post "training"
      end
    end
  end
  resources :places
  resources :players
  resources :trainings, only: [:show, :destroy]
  resources :user_prohibitions


  match "/banned" => "banned#index", as: :banned

  match "/complete" => "complete#edit", as: :complete
  put "/complete_user" => "complete#update", as: :complete_user

  match "/profile" => "profile#index", as: :profile
  match "/profile/informations" => "profile#informations", as: :profile_informations
  match "/profile/update" => "profile#update", as: :profile_update
  match "/profile/about" => "profile#about", as: :profile_about

  match "/search" => "search#index", as: :search
  match "/find" => "search#find", as: :find
  match "/board" => "board#index", as: :board

  root to: "home#index"
  
end

app/models/message.rb
class Message < ActiveRecord::Base

  is_private_message
  
  # The :to accessor is used by the scaffolding,
  # uncomment it if using it or you can remove it if not
  #attr_accessor :to
  
end

app/controllers/messages_controller.rb
class MessagesController < AuthenticatedController
  def index
    @messages = current_user.received_messages
  end

  def sent
    @messages = current_user.sent_messages
  end

  def show
    @message = Message.read_message(params[:id], current_user)
  end

  def new
    @recipient = User.find(params[:person_id])
    @message = Message.new

    if params[:message_id]
      parent_message      = Message.find(params[:message_id])
      @message.subject    = "[RE]: #{parent_message.subject}" if parent_message
    end
  end

  def create
    @recipient = User.find(params[:person_id])
    @message = Message.new
    @message.subject = params[:message][:subject] if params[:message]
    @message.body = params[:message][:body]       if params[:message]
    @message.sender = current_user
    @message.recipient = @recipient
    if @message.save
      redirect_to sent_messages_path, notice: "Sent message successful"
    else
      render :new
    end
  end

  def destroy
    Message.find(params[:id]).mark_deleted(current_user)
    redirect_to messages_path
  end
end

app/views/messages/_navigation.html.haml
%ul.button-group.radius.center
	%li= link_to "Inbox", messages_path, :class =>"button radius small"
	%li= link_to "Sent", sent_messages_path, :class =>"button radius small"

app/views/messages/index.html.haml
.twelve.columns
  %h1 Messages
  = render 'navigation'
  .row
    .twelve.columns
      %table.messageList
        %thead
          %th.status Unread
          %th.subject Subject
          %th.action
        %tbody
          - @messages.each do |message|
            %tr
              %td= message.read_at?
              %td= link_to message.subject, message_path(message)
              %td= link_to "remove", message_path(message), method: :delete, :class => "radius button alert tiny"

app/views/messages/new.html.haml
.twelve.columns
  %h1 New message
  = simple_form_for @message, url: person_messages_path(@recipient) do |f|
    = f.input :subject
    = f.input :body
    = f.button :submit, "Send message", :class => "radius button"

app/views/messages/sent.html.haml
.twelve.columns
  %h1 Messages / Sent
  = render 'navigation'
  %table.messageList
    %thead
      %th.status Unread
      %th.subject Subject
      %th.action
    %tbody
      - @messages.each do |message|
        %tr
          %td= #message.read_at?
          %td= link_to message.subject, message_path(message)
          %td= link_to "remove", message_path(message), method: :delete, :class => "radius button alert tiny"

app/views/messages/show.html.haml
.twelve.columns
	%h1 Message

	%p 
		<strong>Sender:</strong> #{@message.sender.name}
	%p
		<strong>Recipient:</strong> #{@message.recipient.name}

	%h5
		<strong>Title:</strong> #{@message.subject}
	%p= @message.body

	= link_to "reply", new_person_message_path(@message.sender,  message_id: @message), :class => "radius button"