config/routes.rb
CoachApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { registrations: "registrations" }

  resources :contacts
  resources :events
  resources :friendships #, only: [:delete]
  resources :invitations, except: [:show, :edit]
  resources :messages, only: [:index, :sent, :show, :destroy] do
    collection do
      get 'sent'
    end
  end
  resources :parameters
  resources :people do
    resources :messages, only: [:new, :create]
    resources :invitations do # , only: [:create] do
      collection do
        post "training"
      end
    end
  end
  resources :places
  resources :players
  resources :trainings, only: [:show, :destroy]
  resources :user_prohibitions


  match "/banned" => "banned#index", as: :banned

  match "/complete" => "complete#edit", as: :complete
  put "/complete_user" => "complete#update", as: :complete_user

  match "/profile" => "profile#index", as: :profile
  match "/profile/informations" => "profile#informations", as: :profile_informations
  match "/profile/update" => "profile#update", as: :profile_update
  match "/profile/about" => "profile#about", as: :profile_about

  match "/search" => "search#index", as: :search
  match "/find" => "search#find", as: :find
  match "/board" => "board#index", as: :board

  root to: "home#index"
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @coaches = []
    @users = []
    @places = []

    if params[:search].present?
      results = User.search(params[:search], order: :last_name, conditions: { status: "active" })
      if results
        @coaches = results.select { |u| u.coach? }
        @users = results.reject   { |u| u.coach? }
      end
    end

    if params[:city].present? && params[:discipline].present?
      results = User.active.joins(:disciplines).where("disciplines.name like ? and users.city like ?", params[:discipline], params[:city]).uniq
      if results
        @coaches = results.select { |u| u.coach? }
        @users = results.reject   { |u| u.coach? }
      end
    elsif params[:city].present?
      results = User.active.where("city like ?", params[:city])
      if results
        @coaches = results.select { |u| u.coach? }
        @users = results.reject   { |u| u.coach? }
      end
    elsif params[:discipline].present?
      results = User.active.joins(:disciplines).where("disciplines.name like ?", params[:discipline]).uniq
      if results
        @coaches = results.select { |u| u.coach? }
        @users = results.reject   { |u| u.coach? }
      end
    end

    if params[:user]
      @coaches = User.custom_search(params[:user])
    end

    if params[:location] && params[:place]
      if params[:location][:city].present? && params[:place][:name].present?
        @places = Place.joins(:location).where("locations.city = ?", params[:location][:city]).where(name: params[:place][:name])
      elsif params[:location][:city].present?
        @places = Place.joins(:location).where("locations.city = ?", params[:location][:city])
      elsif params[:place][:name].present?
        @places = Place.where(name: params[:place][:name])
      end
    end
  end

  def find
  end

end

app/views/search/find.html.haml
.twelve.columns
  %h1 Find
  = simple_form_for User.new, url: find_path, method: :get do |f|
    = f.input :city, input_html: { value: (params[:user].present? ? params[:user][:city] : "") }
    = f.button :submit, "Search", id: "user_search", :class => "radius button"

  %h2 Or find place!
  = form_tag url: find_path, method: :get do
    = label_tag 'location[city]', "City"
    = text_field_tag "location[city]"
    %br
    = label_tag "place[name]", "Name"
    = text_field_tag "place[name]"
    %br
    = submit_tag "Serach", id: "place_search"

app/views/search/index.html.haml
.alert-box.secondary
  "Search #{params[:search]}"

%h3 Places
- unless @places.empty?
  %ol
  - @places.each do |place|
    %li= link_to place.name, place

%h3 Coaches
- unless @coaches.empty?
  %ol
  - @coaches.each do |coach|
    %li= link_to coach.name, player_path(coach)

%h3 Users
- unless @users.empty?
  %ol
  - @users.each do |user|
    %li= link_to user.name, player_path(user)