config/routes.rb
CoachApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { registrations: "registrations" }

  resources :contacts
  resources :events
  resources :friendships #, only: [:delete]
  resources :invitations, except: [:show, :edit]
  resources :messages, only: [:index, :sent, :show, :destroy] do
    collection do
      get 'sent'
    end
  end
  resources :parameters
  resources :people do
    resources :messages, only: [:new, :create]
    resources :invitations do # , only: [:create] do
      collection do
        post "training"
      end
    end
  end
  resources :places
  resources :players
  resources :trainings, only: [:show, :destroy]
  resources :user_prohibitions


  match "/banned" => "banned#index", as: :banned

  match "/complete" => "complete#edit", as: :complete
  put "/complete_user" => "complete#update", as: :complete_user

  match "/profile" => "profile#index", as: :profile
  match "/profile/informations" => "profile#informations", as: :profile_informations
  match "/profile/update" => "profile#update", as: :profile_update
  match "/profile/about" => "profile#about", as: :profile_about

  match "/search" => "search#index", as: :search
  match "/find" => "search#find", as: :find
  match "/board" => "board#index", as: :board

  root to: "home#index"
  
end

app/views/shared/_footer.html.haml
%hr
%h5 Footer

app/views/shared/_header.html.haml
- if current_user
  .fullContent
    .row
      .twelve.columns
        %nav.top-bar
          %ul
            / Title Area
            %li.name
              %h1
                = link_to "Coach App", root_path
            %li.toggle-topbar
              %a{:href => "#"}
          %section
            / Left Nav Section
            %ul.left
              %li.divider
              %li
                - if current_user.unread_messages?
                  = link_to "Messages (#{current_user.unread_message_count})", messages_path, id: "messages", :class => "foundicon-mail newThing"
                - else
                  = link_to "Messages", messages_path, id: "messages", :class => "foundicon-mail"
              %li
                - invitations_count = current_user.invitation_requests.where(status: "expectant").count
                - if invitations_count
                  = link_to "Invitations (#{invitations_count})", invitations_path, :class => "foundicon-plus newThing"
                - else
                  = link_to "Invitations", invitations_path, :class => "foundicon-plus"
              %li
                = link_to "Contacts", contacts_path, :class => "foundicon-address-book"
              %li.searcher
                = render "shared/search"
            / Right Nav Section
            %ul.right
              %li.divider.show-for-medium-and-up
              %li= link_to "Profile", profile_path
              %li.divider
              %li{ id: "" }
                = link_to "Logout", destroy_user_session_path, method: :delete
- else
  .fullContent.NavMore
    .row
      .twelve.columns
        %nav.top-bar
          %ul
            / Title Area
            %li.name
              %h1
                = link_to "Coach App", root_path
            %li.toggle-topbar
              %a{:href => "#"}
          %section
            / Right Nav Section
            %ul.right
              %li.searcher
                = render "shared/search"

              %li{ id: "" }
                = link_to "Sign up", new_user_registration_path
              %li{ id: "" }
                = link_to "Login", new_user_session_path

app/views/shared/_notice.html.haml
.row
  .twelve.columns
    / %p= "Welcome #{current_user.first_name}"

- if flash
  .row
    .twelve.columns#alertBoxes
      - if flash[:notice]
        .alert-box.success
          = flash[:notice]
          %a.close{ href: "" } &times;

      - if flash[:alert]
        .alert-box.alert
          = flash[:alert]
          %a.close{ href: "" } &times;

app/views/shared/_search.html.haml
.search
  = form_tag search_path do
    .search_input
      = search_field_tag "search", params[:search], :placeholder => "Search..."
    .search_submit
      = button_tag "Search", :class => 'button expand postfix foundicon-search'

app/views/shared/_user_information.html.haml
.seven.columns.centered.end
  = simple_form_for current_user, url: url, method: :put do |f|
    .form-inputs
      = f.input :first_name
      = f.input :last_name
      = f.input :birth, as: :date, start_year: Date.today.year - 100, end_year: Date.today.year - 12 , order: [:day, :month, :year] 

      = f.label :country
      = country_select("user", "country")

      = f.input :city
      = f.input :phone

      %label Avatar
      = image_tag(current_user.avatar_url, size: "100x100") if current_user.avatar?
      = f.file_field :avatar
      = f.hidden_field :avatar_cache

    .form-actions
      = f.button :submit, "Save", class: "nice button center", id: "save_user_information"