config/routes.rb
CoachApp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { registrations: "registrations" }

  resources :contacts
  resources :events
  resources :friendships #, only: [:delete]
  resources :invitations, except: [:show, :edit]
  resources :messages, only: [:index, :sent, :show, :destroy] do
    collection do
      get 'sent'
    end
  end
  resources :parameters
  resources :people do
    resources :messages, only: [:new, :create]
    resources :invitations do # , only: [:create] do
      collection do
        post "training"
      end
    end
  end
  resources :places
  resources :players
  resources :trainings, only: [:show, :destroy]
  resources :user_prohibitions


  match "/banned" => "banned#index", as: :banned

  match "/complete" => "complete#edit", as: :complete
  put "/complete_user" => "complete#update", as: :complete_user

  match "/profile" => "profile#index", as: :profile
  match "/profile/informations" => "profile#informations", as: :profile_informations
  match "/profile/update" => "profile#update", as: :profile_update
  match "/profile/about" => "profile#about", as: :profile_about

  match "/search" => "search#index", as: :search
  match "/find" => "search#find", as: :find
  match "/board" => "board#index", as: :board

  root to: "home#index"
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/views/players/show.html.haml
.twelve.columns
  %h1 Profile:  #{@user.first_name} #{@user.last_name}

  - if current_user && @user != current_user
    %ul.button-group.radius
      - invitations = current_user.invitations.where(invited_id: @user.id)
      - if current_user.friends.include?(@user)
        %p 
          You are friend
          - friend = current_user.friendships.find_by_friend_id(@user)
          - friend = current_user.inverse_friendships.find_by_user_id(@user) if friend.blank?
          = link_to "Remove from friends", friendship_path(friend), method: :delete, confirm: "Are you sure?"
      - elsif invitations.present?
        %p You're sent invitation to friend now.
      - else
        - unless current_user.friends.include?(@user)
          = button_to "Add to friends", person_invitations_path(@user)

      - if invitations.present? && invitations.select(&:training).present?
        %p You're sent training invitation to user now.
      - else
        - if current_user.trained_users.include?(@user)
          - training = current_user.trainings.find_by_user_id(@user.id)
          .div
            %p
              = "You are coach for this user."
              = link_to "Training", training_path(training)
        - else
          = button_to "Add to training", training_person_invitations_path(@user)
      - if current_user.user_coaches.include?(@user)
        .div
          %p
            - training = current_user.inverse_trainings.find_by_coach_id(@user.id)
            = "You are trained for this user."
            = link_to "Training", training_path(training)        
    
  %hr

  = link_to "send message", new_person_message_path(@user), :class => "radius button small"

  %hr
  .four.columns
    %h3 Informations
    .avatar
      = image_tag @user.avatar.url, size: "100x100" if @user.avatar?
    %p
      <strong>Name:</strong> #{@user.first_name}
    %p
      <strong>Last name:</strong> #{@user.last_name}
    %p
      <strong>City:</strong> #{@user.city}
    %p
      <strong>Disciplines:</strong>
      %ul
        - @user.disciplines.each do |discipline|
          %li= discipline.name

  .four.columns
    - if current_user && current_user.coach && current_user.trained_users.include?(@user)
      %h3 Parameters
      %ul.circle
        - @user.parameters.each do |parameter|
          %li
            <strong>Height: </strong> #{parameter.height} cm
          %li
            <strong>Weight: </strong> #{parameter.weight} cm
  .four.columns
    - if current_user && current_user.coach && current_user.trained_users.include?(@user)
      %h3 Prohibitions
      %ul.circle
        - @user.prohibitions.each do |prohibition|
          %li= prohibition.name